name: Kasper's Serenity
description: Blogging about Being Happy
meta_description: "Kasper  blogs about the art of happiness, serenity & contentment."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: roachhd.github.io/kasper/
url: 'http://roachhd.github.io/kasper/'

# Details for the RSS feed generator
url:            'http://roachhd.github.io/kasper/'
author:         'Katie Ball'
