name: Kasper's Serenity
description: A Quiet and Happy Corner of the Net
meta_description: "Kasper blogs about the art of happiness, serenity & contentment. It's quiet and peaceful here. Everyone is welcome :smile: ."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /kasper/
url: 'http://roachhd.github.io/kasper/'

# Details for the RSS feed generator
url:            'http://roachhd.github.io/kasper/'
author:         'Katie Ball'

# Disqus
disqus_shortname: katieballme

#google analytics
analytics: UA-47871720-3

author:
  name: Kasper

# Use the following plug-ins
# Emoji please!
# Create a sitemap using the official Jekyll sitemap gem
gems:
  - jemoji
  - jekyll-sitemap
